name: Release

on:
  push:
    tags:
      - 'v*'
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: |
        npm install
        cd src/webview && npm install && cd ../..

    - name: Build webview
      run: |
        cd src/webview && npm run build && cd ../..

    - name: Build extension
      run: npm run compile

    - name: Install vsce
      run: npm install -g @vscode/vsce

    - name: Update version from tag
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        npm version $TAG --no-git-tag-version

    - name: Package extension
      run: vsce package

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: '*.vsix'
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
